import React from "react";
import Button, {
	SecondaryButtonComponent as SecondaryButton
} from "../components/Button";
const Home = () => {
	return (
		<h1>
			This is homepage
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<Button label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
			<SecondaryButton label="ABC" />
		</h1>
	);
};

export default Home;
